### ISSUE TITLE
Failed to obtain access token

### ISSUE THREAD

**Issue by misbach** [jaredhanson/passport-familysearch#3]
I'm getting the following error after entering FS credentials. Any ideas what's wrong?

failed to obtain access token (status: 400 data:
    {
        "error_description":"Public client provided client credential: 3K7D-3DF4-F734-RCW5-9FHT-CSV4-CMLS-2VRZ",
        "error":"invalid_request"
    }
)
at /[app_path]/node_modules/passport-familysearch/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:125:38
at /[app_path]/node_modules/passport-familysearch/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:160:18
at passBackControl (/[app_path]/node_modules/passport-familysearch/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:105:9)
at IncomingMessage.<anonymous> (/[app_path]/node_modules/passport-familysearch/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:124:7)
at IncomingMessage.EventEmitter.emit (events.js:117:20)
at _stream_readable.js:920:16
at process._tickCallback (node.js:415:13)

**Comment by misbach** [comment]
I should add that this problem is when trying to get it working with localhost. The oauth process works fine when I deploy to my production environment.
